"""
jd_config.py — Hard-coded JD analysis for the Redrob Senior AI Engineer JD.

This encodes the MEANING of the JD, not just its keywords.
Generated by analyzing the JD document deeply.

Key insight from JD: "The right answer involves reasoning about the gap between
what the JD says and what the JD means."
"""

from datetime import date

JD_PROFILE = {

    # =========================================================================
    # ROLE IDENTITY
    # =========================================================================
    "role_title": "Senior AI Engineer",
    "company_stage": "Series A",
    "location_preferred": ["Pune", "Noida", "Hyderabad", "Mumbai", "Delhi NCR", "Delhi", "Bangalore"],
    "location_country": "India",
    "exp_years_min": 5,
    "exp_years_max": 9,
    "exp_years_ideal": (6, 8),
    "notice_period_preferred_days": 30,   # "sub-30" preferred, buyout up to 30

    # =========================================================================
    # MUST-HAVE SKILLS (hard technical requirements)
    # These are the non-negotiables. Named semantically, not by keyword.
    # =========================================================================
    "must_have_skills": [
        # Embedding / retrieval family
        "embeddings", "sentence-transformers", "openai embeddings", "bge", "e5",
        "semantic search", "dense retrieval", "vector search", "embedding",

        # Vector DB / hybrid search
        "pinecone", "weaviate", "qdrant", "milvus", "faiss", "opensearch",
        "elasticsearch", "vector database", "vector store", "hybrid search",
        "chroma", "annoy",

        # Ranking / retrieval systems
        "ranking", "retrieval", "recommendation system", "search", "bm25",
        "information retrieval", "candidate ranking", "re-ranking", "reranking",
        "learning to rank",

        # Evaluation frameworks (explicit must-have)
        "ndcg", "mrr", "map", "evaluation", "a/b testing", "offline eval",
        "ranking evaluation", "benchmark",

        # Python (explicit must-have)
        "python",
    ],

    # =========================================================================
    # STRONG-SIGNAL SKILLS (differentiate strong from average candidates)
    # =========================================================================
    "strong_signal_skills": [
        # LLM / fine-tuning (nice-to-have but differentiating)
        "llm", "large language model", "fine-tuning", "lora", "qlora", "peft",
        "rag", "retrieval augmented generation", "langchain", "llama",
        "transformers", "bert", "gpt", "instruction tuning",

        # ML production
        "mlops", "model serving", "inference optimization", "triton",
        "torchserve", "bentoml", "ray", "distributed training",

        # NLP (core to role)
        "nlp", "natural language processing", "text classification",
        "named entity recognition", "question answering",

        # Learning to rank specific
        "xgboost", "lightgbm", "learning to rank", "lambdamart", "ranknet",
    ],

    # =========================================================================
    # CAREER SIGNAL KEYWORDS
    # Used to detect "product company" experience vs consulting
    # =========================================================================
    "product_company_signals": [
        # What a product company looks like in career history
        "startup", "product", "saas", "platform", "scale", "production",
        "deployed", "shipped", "launched", "users", "a/b test",
        "real-time", "latency", "throughput",
    ],

    "consulting_red_flag_companies": [
        "tcs", "infosys", "wipro", "accenture", "cognizant", "capgemini",
        "hcl", "tech mahindra", "mphasis", "hexaware", "mindtree",
        "l&t infotech", "lti", "ltimindtree",
    ],

    # =========================================================================
    # HARD DISQUALIFIERS (from JD "What we explicitly do NOT want")
    # =========================================================================
    "hard_disqualifiers": {
        # Pure research without production (checked via career history)
        "no_production_experience": True,
        # Only consulting companies entire career
        "only_consulting_career": True,
        # Primary focus CV/speech/robotics without NLP/IR
        "wrong_domain_focus": True,
    },

    # =========================================================================
    # BEHAVIORAL SIGNAL WEIGHTS
    # The signals doc says these are "more predictive" than static profile
    # =========================================================================
    "behavioral_weights": {
        "open_to_work":              0.15,   # Binary — is this person actually available?
        "recency":                   0.20,   # Last active date — core proxy for availability
        "recruiter_response_rate":   0.20,   # JD explicitly says down-weight low-response candidates
        "interview_completion_rate": 0.10,   # Reliability signal
        "profile_completeness":      0.10,   # Seriousness of search
        "github_activity":           0.10,   # JD asks for "open source contributions in AI/ML space"
        "saved_by_recruiters_30d":   0.08,   # Social proof — other recruiters liked them
        "notice_period_fit":         0.07,   # JD: "sub-30 preferred"
    },

    # =========================================================================
    # SCORING DIMENSION WEIGHTS
    # Tuned to the NDCG@10 metric (top-10 quality weighted 50%)
    # Prioritizes getting top-10 perfect over covering the full 100
    # =========================================================================
    "dimension_weights": {
        "skill_match":       0.35,   # Core technical fit
        "career_trajectory": 0.25,   # Growth signal, product vs consulting, domain fit
        "behavioral":        0.25,   # Platform signals — actual availability
        "education":         0.05,   # Tier 1/2 is nice but not decisive
        "location_fit":      0.10,   # India + preferred cities
    },

    # =========================================================================
    # LOCATION SCORING
    # =========================================================================
    "location_score": {
        "Pune": 1.0, "Noida": 1.0,
        "Hyderabad": 0.9, "Mumbai": 0.9, "Delhi": 0.9, "Delhi NCR": 0.9,
        "Bengaluru": 0.85, "Bangalore": 0.85, "Chennai": 0.75,
        "India": 0.6,   # Other India location
        "Outside India": 0.2,  # "case-by-case, don't sponsor visas"
    },

    # =========================================================================
    # EXPERIENCE SCORING CURVE
    # 5-9 is stated range; 6-8 is ideal from JD "how to read between the lines"
    # =========================================================================
    "experience_scoring": {
        "below_4": 0.3,
        "4_to_5":  0.65,
        "5_to_6":  0.80,
        "6_to_8":  1.0,   # ideal band
        "8_to_10": 0.85,
        "10_to_13": 0.65,
        "above_13": 0.45,  # JD warns against "stagnant senior"
    },

    # =========================================================================
    # SKILL ASSESSMENT RELEVANT SKILLS
    # These are skills where Redrob's own assessment scores matter
    # =========================================================================
    "relevant_assessment_skills": [
        "python", "nlp", "machine learning", "deep learning",
        "sql", "data science", "statistics",
        "fine-tuning llms", "llm", "transformers",
    ],

    # Reference date for recency calculations
    "reference_date": date(2026, 6, 1),

    # Salary range the company is likely targeting (Series A, Pune/Noida)
    # Candidates who are WAY above this range are unlikely to join
    "salary_range_inr_lpa": {"min": 25, "max": 55},
}
